name: rebuild
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  google_fonts: ^6.3.2
  carousel_slider: ^5.1.1
  flutter_localizations:
    sdk: flutter

  vector_math: 2.1.4
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  jwt_decoder: ^2.0.1
  nsfw_detector_flutter: ^1.0.5
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  flutter_map_tile_caching: ^10.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/splash_logo.jpg
    - assets/images/Logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"
